DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS bags CASCADE;
DROP TABLE IF EXISTS boards CASCADE;
DROP TABLE IF EXISTS cells CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS words CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS tiles CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE actions (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  counter integer not null,
  current_player_number integer,
  game_id bigint not null,
  round_number integer,
  status varchar(255) not null,
  type varchar(255) not null,
  user_id bigint not null,
  primary key (id)
);
CREATE TABLE bags (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  enabled tinyint default 1 not null,
  language varchar(255) not null,
  name varchar(255) not null,
  tile_count integer not null,
  primary key (id)
);
CREATE TABLE boards (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  column_size integer not null,
  enabled tinyint default 1 not null,
  name varchar(255) not null,
  row_size integer not null,
  primary key (id)
);
CREATE TABLE cells (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  board_id bigint not null,
  "cell_number" integer,
  color varchar(255),
  "column_number" integer,
  has_bottom tinyint default 1 not null,
  has_left tinyint default 1 not null,
  has_right tinyint default 1 not null,
  has_top tinyint default 1 not null,
  letter_value_multiplier integer,
  "row_number" integer,
  center tinyint default 0 not null,
  word_score_multiplier integer,
  primary key (id)
);
CREATE TABLE chats (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  game_id bigint not null,
  message varchar(255) not null,
  user_id bigint not null,
  primary key (id)
);
CREATE TABLE games (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  action_counter integer not null,
  active_player_count integer not null,
  bag_id bigint not null,
  board_id bigint not null,
  "current_player_number" integer,
  duration integer not null,
  end_date timestamp,
  expected_player_count integer not null,
  name varchar(255) not null,
  owner_id bigint not null,
  round_number integer,
  start_date timestamp,
  status varchar(255) not null,
  primary key (id)
);
CREATE TABLE players (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  game_id bigint,
  joined_date datetime default now() not null,
  left_date timestamp,
  user_id bigint,
  "player_number" integer,
  score integer not null,
  primary key (id)
);
CREATE TABLE roles (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  enabled tinyint default 1 not null,
  type varchar(255) not null,
  primary key (id)
);
CREATE TABLE tiles (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  bag_id bigint not null,
  count integer,
  letter varchar(255),
  "value" integer,
  vowel tinyint default 0 not null,
  primary key (id)
);
CREATE TABLE user_roles (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  enabled tinyint default 1 not null,
  type varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);
CREATE TABLE users (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  account_non_expired tinyint default 1 not null,
  account_non_locked tinyint default 1 not null,
  credentials_non_expired tinyint default 1 not null,
  email varchar(255) not null,
  enabled tinyint default 1 not null,
  password varchar(255) not null,
  username varchar(255) not null,
  primary key (id)
);
CREATE TABLE words (
  id bigint generated by default as identity,
  created_date datetime default now() not null,
  last_updated_date timestamp,
  game_id bigint not null,
  "player_number" integer not null,
  round_number integer not null,
  score integer not null,
  word varchar(255) not null,
  primary key (id)
);
ALTER TABLE roles add constraint UK_ROLE_TYPE unique (type);
ALTER TABLE user_roles add constraint UK_USER_ROLE unique (username, type, enabled);
ALTER TABLE users add constraint UK_USER_NAME unique (username);
ALTER TABLE users add constraint UK_USER_EMAIL unique (email);